# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"D\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"S\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x0c\n\x04role\x18\x04 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xa8\x01\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x10\n\x08username\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0c\n\x04role\x18\x06 \x01(\t\x12\x11\n\tneeds_otp\x18\x07 \x01(\x08\x12\x10\n\x08is_admin\x18\x08 \x01(\x08\x12\x10\n\x08otp_code\x18\t \x01(\t\"5\n\x10VerifyOTPRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08otp_code\x18\x02 \x01(\t\"5\n\x11VerifyOTPResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x12GenerateOTPRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"5\n\x13GenerateOTPResponse\x12\x10\n\x08otp_code\x18\x01 \x01(\t\x12\x0c\n\x04sent\x18\x02 \x01(\x08\x32\x80\x02\n\x0b\x41uthService\x12=\n\x0cRegisterUser\x12\x15.auth.RegisterRequest\x1a\x16.auth.RegisterResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12<\n\tVerifyOTP\x12\x16.auth.VerifyOTPRequest\x1a\x17.auth.VerifyOTPResponse\x12\x42\n\x0bGenerateOTP\x12\x18.auth.GenerateOTPRequest\x1a\x19.auth.GenerateOTPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=88
  _globals['_REGISTERRESPONSE']._serialized_start=90
  _globals['_REGISTERRESPONSE']._serialized_end=173
  _globals['_LOGINREQUEST']._serialized_start=175
  _globals['_LOGINREQUEST']._serialized_end=225
  _globals['_LOGINRESPONSE']._serialized_start=228
  _globals['_LOGINRESPONSE']._serialized_end=396
  _globals['_VERIFYOTPREQUEST']._serialized_start=398
  _globals['_VERIFYOTPREQUEST']._serialized_end=451
  _globals['_VERIFYOTPRESPONSE']._serialized_start=453
  _globals['_VERIFYOTPRESPONSE']._serialized_end=506
  _globals['_GENERATEOTPREQUEST']._serialized_start=508
  _globals['_GENERATEOTPREQUEST']._serialized_end=545
  _globals['_GENERATEOTPRESPONSE']._serialized_start=547
  _globals['_GENERATEOTPRESPONSE']._serialized_end=600
  _globals['_AUTHSERVICE']._serialized_start=603
  _globals['_AUTHSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)
